# -*- coding: utf-8 -*-
"""Assignment-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_dKoY_gWGUrE3RpJThfugcFK1UJkwLpp

1.Develop a code for below scenario
"""

list=['money','rooster','dog','pig','rat','ox','tiger','rabbit','dragon','snake','horse','sheep']
year=input("enter year: ")
d=int(year)%12
print(list[d])

"""2 A Quick Fox Transport Co. wants to develop an application for calculating amount based on distance and weight of goods. The charges (Amount) to be calculated as per rates given below."""

load=int(input("enter the weight: "))
distance=int(input("enter the distance"))
if distance>=500:
  if load>=100 :
    charged_amount=distance*5
    print('the amount to be charged is',charged_amount)
  elif (load>=10) and (load<100):
    charged_amount=distance*6
    print('the amount to be charged is',charged_amount)
  else:
    charged_amount=distance*7
    print('the amount to be charged is',charged_amount)
else:
  if distance<500:
    if load>=100:
      charged_amount=diatance*8
      print('the amount to be charged is',charged_amount)
    else:
      charged_amount=distance*5
      print('the amount to be charged',charged_amount)

"""3.An Entertaiment paradise.
  A theater in Delhi wants to develop a computerized Booking System. The theater offers different types of seats. The Ticket rates are- Stalls- Rs. 625/-, Circle- Rs.750/-, Upper Class- Rs.850/- and Box- Rs.1000/-. A discount is gien 10% of total amount if tickets are purchased on Cash. In case of credit card holders 5% discount is given.
"""

computerized booking system
seats={"stall":625,"circle":750,"upper circle":850,"box":1000}
print('avialabe seats are',seats)
payment=input('enter payment method:')
if payment=='cash':
  print('select the seats \n  1.stall \n 2.circle \n  3.upper class \n  4.box')
  x=input("enter the name of the seat required:")
  y=int(input("number of seats required:"))
  amount=seats[x]*y
  discount=amount*(10/100)
  total_amount=amount-discount
  print('total amount is :',total_amount)
else:
  if payment=='credit':
    print('select the seats \n  1.stall \n 2.circle \n  3.upper class \n  4.box')
    x=input("enter the name of the seat required:")
    y=int(input("number of seats required:"))
    amount=seats[x]*y
    discount=amount*(5/100)
    total_amount=amount-discount
    print('total amount is :',total_amount)

"""4.Develop a program that calculates the energy needed to heat water from an initial temperature to a final temperature. Your program should prompt the user to enter the amount of water in kilograms and the initial and final temperatures of the water. The formula to compute the energy is 
Q = M * (finalTemperature  initialTemperature) * 4184.
where M is the weight of water in kilograms, temperatures are in degrees Celsius,  and energy Q is measured in joules.
"""

# Energy needed to heat water
weight=int(input("enter weight of water in kilograms: "))
initial=int(input("enter initial temperature in celsius :"))
final=int(input("enter final temperature in celsius :"))
energy=weight*(final-initial)*4184
print('energy required to heat water is:',energy)

"""5.Develop a program that prompts user to enter month and  print
Winter  -   December ,January and February.
Spring  -   March ,April and May.
Summer  --- June ,July, August.
Autumn   -- September ,October, November.
"""

x=input("enter month name in small letters  :")
if (x=='january') or (x=='february') or (x=='december'):
  print('season=winter')
elif (x=='march') or (x=='april') or (x=='may'):
  print('season=spring')
elif (x=='june') or (x=='july') or (x=='august'):
  print('season=summer')
elif (x=='september') or (x=='october') or (x=='november'):
  print('season=Autumn')
else:
  print('no month available')

"""6.Body Mass Index"""

weight=float(input("enter weight in pounds :"))
height=float(input("enter height in inches :"))
w_kg=weight*0.45359237
h_meters=height*0.0254
BMI=(w_kg)/((h_meters)**2)
if BMI<18.5:
  print("Underweight")
elif (BMI<=18.5) and (BMI<25.0):
  print("Normal")
elif (BMI<=25.0) and (BMI<30.0):
  print("Overweight")
elif BMI<=30.0:
  print('Obese')
else:
  print('none')

"""7.Print all palindrome numbers between 1 to 1000."""

minimum = int(input(" Please Enter the Minimum Value : "))
maximum = int(input(" Please Enter the Maximum Value : "))
for num in range(minimum, maximum + 1):
    temp = num
    reverse = 0
    
    while(temp > 0):
        Reminder = temp % 10
        reverse = (reverse * 10) + Reminder
        temp = temp //10

    if(num == reverse):
        print("%d " %num, end = '  ')

"""8.Print all Armstrong numbers between 1 to 1000."""

lower = int(input("Enter lower range: "))
upper = int(input("Enter upper range: "))
 
for num in range(lower,upper + 1):
   sum = 0
   temp = num
   while temp > 0:
       digit = temp % 10
       sum += digit ** 3
       temp //= 10
 
   if num == sum:
       print(num)

"""9.Write a program that reads an integer between 100 and 1000 and adds all the digits in the integer"""

n=int(input("Enter a number:"))
total=0
if (n>100) and (n<1000):
  while(n>0):
    dig=n%10
    total=total+dig
    n=n//10
else:
  print('number is not in range')
print("The total sum of digits is:",total)

"""10. Write a Java program which iterates the integers from 1 to 100. For multiples of three print "Fizz" instead of the number and print "Buzz" for the multiples of five. When number is divided by both three and five, print "fizz buzz"."""

for i in range(1,100):
  if i%3==0 and i%5==0:
    print('Fizz Buzz',i) 
  elif i%3==0:
    print('FIZZ',i) 
  elif i%5==0:
    print('Buzz',i)

"""11.Spider Problem: A spider present at the bottom of the well of height H, needs to get out of it, using the slippery wall of the well. It decides to climb up the well; it goes up U meters and slips down D meters in one single step. So, in each step it covers (U-D) meters, and if the spider gets out of the well by covering U meters in the last step it doesnt a slip back. For example, if the spider climbs up 5 meters and slips down by 3 meters in a single step, it covers (U - D) m in each step and 96 m in 48 steps, but in the 49th step it climbs up 5 m and reaches out of the well and it will not slip down and the step is counted as one step."""

H=int(input('enter height of the of the well :'))
U=int(input('enter step up meters :'))
D=int(input('enter step down meters :'))
h=0
step=0
while H>h :
  h=h+U
  step=step+1
  h=h-D
print('number of steps :', step)